
package View.Login;

import Controller.DataBase;
import Controller.LoginController;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class LoginInterface extends javax.swing.JFrame {

    private LoginController controller;
    int xMouse,  yMouse;

    public LoginInterface() throws IOException {
        initComponents();
        controller = new LoginController();
        this.setLocationRelativeTo(null);
        
        DataBase DB = new DataBase();
        DB.StartDataBase();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        SesionText = new javax.swing.JLabel();
        UsuarioPNG = new javax.swing.JLabel();
        UserText = new javax.swing.JLabel();
        UserNameTextField = new javax.swing.JTextField();
        UsuarioSeparator = new javax.swing.JSeparator();
        PasswordPNG = new javax.swing.JLabel();
        PasswordText = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        PasswordSeparator = new javax.swing.JSeparator();
        BlackBanner = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        GorritoPNG = new javax.swing.JLabel();
        moveBar = new javax.swing.JPanel();
        exitBottonText = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        BackGround.setBackground(new java.awt.Color(255, 255, 255));
        BackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SesionText.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        SesionText.setText("Iniciar Sesión");
        BackGround.add(SesionText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 250, 40));

        UsuarioPNG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modo-retrato (2).png"))); // NOI18N
        BackGround.add(UsuarioPNG, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 20, 20));

        UserText.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        UserText.setText("USUARIO");
        BackGround.add(UserText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 190, 30));

        UserNameTextField.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        UserNameTextField.setForeground(new java.awt.Color(204, 204, 204));
        UserNameTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        UserNameTextField.setText("Ingrese su nombre de usuario");
        UserNameTextField.setToolTipText("");
        UserNameTextField.setBorder(null);
        UserNameTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UserNameTextFieldMousePressed(evt);
            }
        });
        UserNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameTextFieldActionPerformed(evt);
            }
        });
        UserNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UserNameTextFieldKeyPressed(evt);
            }
        });
        BackGround.add(UserNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 460, 40));
        BackGround.add(UsuarioSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 460, 10));

        PasswordPNG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contrasena (1).png"))); // NOI18N
        BackGround.add(PasswordPNG, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 20, 20));

        PasswordText.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        PasswordText.setText("CONTRASEÑA");
        BackGround.add(PasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 190, 30));

        PasswordField.setForeground(new java.awt.Color(153, 153, 153));
        PasswordField.setText("ingresecontraseña");
        PasswordField.setBorder(null);
        PasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PasswordFieldMousePressed(evt);
            }
        });
        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        PasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordFieldKeyPressed(evt);
            }
        });
        BackGround.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 460, 30));
        BackGround.add(PasswordSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 460, 10));

        BlackBanner.setBackground(new java.awt.Color(36, 37, 42));
        BlackBanner.setForeground(new java.awt.Color(161, 162, 171));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/portrait.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Bienvenido");

        javax.swing.GroupLayout BlackBannerLayout = new javax.swing.GroupLayout(BlackBanner);
        BlackBanner.setLayout(BlackBannerLayout);
        BlackBannerLayout.setHorizontalGroup(
            BlackBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BlackBannerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(35, 35, 35))
        );
        BlackBannerLayout.setVerticalGroup(
            BlackBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlackBannerLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel5)
                .addGap(52, 52, 52)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        BackGround.add(BlackBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 200, 540));

        GorritoPNG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gorro-de-graduacion.png"))); // NOI18N
        BackGround.add(GorritoPNG, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 40, 40));

        moveBar.setBackground(new java.awt.Color(255, 255, 255));
        moveBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moveBarMouseDragged(evt);
            }
        });
        moveBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moveBarMousePressed(evt);
            }
        });

        exitBottonText.setBackground(new java.awt.Color(255, 255, 255));
        exitBottonText.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        exitBottonText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitBottonText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cruzar (2).png"))); // NOI18N
        exitBottonText.setToolTipText("");
        exitBottonText.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitBottonText.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        exitBottonText.setOpaque(true);
        exitBottonText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBottonTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBottonTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBottonTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout moveBarLayout = new javax.swing.GroupLayout(moveBar);
        moveBar.setLayout(moveBarLayout);
        moveBarLayout.setHorizontalGroup(
            moveBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moveBarLayout.createSequentialGroup()
                .addComponent(exitBottonText, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 715, Short.MAX_VALUE))
        );
        moveBarLayout.setVerticalGroup(
            moveBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitBottonText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        BackGround.add(moveBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        jPanel1.setBackground(new java.awt.Color(36, 37, 42));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingresar");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        BackGround.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 160, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed
//AQUI VA LO QUE BORRE
    
    
    
    
    private void moveBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveBarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_moveBarMousePressed

    private void moveBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveBarMouseDragged
        
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_moveBarMouseDragged

    private void UserNameTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserNameTextFieldMousePressed
        
        if (UserNameTextField.getText().equals("Ingrese su nombre de usuario")) {
        UserNameTextField.setText("");
        UserNameTextField.setForeground(Color.black);
        }
        if (String.valueOf(PasswordField.getPassword()).isEmpty()) {
             PasswordField.setText("ingresecontraseña");
            PasswordField.setForeground(Color.gray);
        }
       
    }//GEN-LAST:event_UserNameTextFieldMousePressed

    private void PasswordFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordFieldMousePressed
        
        if (String.valueOf(PasswordField.getPassword()).equals("ingresecontraseña")) {
        PasswordField.setText("");
        PasswordField.setForeground(Color.black);
        }
        if (UserNameTextField.getText().isEmpty()) {
            UserNameTextField.setText("Ingrese su nombre de usuario");
            UserNameTextField.setForeground(Color.gray);
        }
    }//GEN-LAST:event_PasswordFieldMousePressed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        String idUser = UserNameTextField.getText();
        String password = PasswordField.getText();
        boolean response = false;
        try {
            response = controller.isUserValid(idUser, password);
        } catch (IOException ex) {
            Logger.getLogger(LoginInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(response == true){
           JOptionPane.showMessageDialog(this,"LOGIN EXITOSO");
           if (controller.getRole().equals("Student")){
               MenuStudent menuStudent = new MenuStudent();
               menuStudent.setVisible(true);
               this.setVisible(false);  
               this.setLocationRelativeTo(null);
            }
           if(controller.getRole().equals("Teacher")){
               MenuTeacher menuTeacher = new MenuTeacher();
               menuTeacher.setVisible(true);
               this.setVisible(false);
               
           }
           
            
        }else {
            JOptionPane.showMessageDialog(this, "USUARIO Y/O CONTRASEÑA ERRONEA");
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void UserNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameTextFieldActionPerformed

    private void UserNameTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UserNameTextFieldKeyPressed
         if (UserNameTextField.getText().equals("Ingrese su nombre de usuario")) {
        UserNameTextField.setText("");
        UserNameTextField.setForeground(Color.black);
        }
        if (String.valueOf(PasswordField.getPassword()).isEmpty()) {
             PasswordField.setText("ingresecontraseña");
            PasswordField.setForeground(Color.gray);
        }
    }//GEN-LAST:event_UserNameTextFieldKeyPressed

    private void PasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordFieldKeyPressed
        if (String.valueOf(PasswordField.getPassword()).equals("ingresecontraseña")) {
        PasswordField.setText("");
        PasswordField.setForeground(Color.black);
        }
        if (UserNameTextField.getText().isEmpty()) {
            UserNameTextField.setText("Ingrese su nombre de usuario");
            UserNameTextField.setForeground(Color.gray);
        }
    }//GEN-LAST:event_PasswordFieldKeyPressed

    private void exitBottonTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBottonTextMouseExited
        exitBottonText.setBackground(Color.white);
    }//GEN-LAST:event_exitBottonTextMouseExited

    private void exitBottonTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBottonTextMouseEntered
        exitBottonText.setBackground(Color.gray);
    }//GEN-LAST:event_exitBottonTextMouseEntered

    private void exitBottonTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBottonTextMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitBottonTextMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new LoginInterface().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(LoginInterface.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JPanel BlackBanner;
    private javax.swing.JLabel GorritoPNG;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordPNG;
    private javax.swing.JSeparator PasswordSeparator;
    private javax.swing.JLabel PasswordText;
    private javax.swing.JLabel SesionText;
    private javax.swing.JTextField UserNameTextField;
    private javax.swing.JLabel UserText;
    private javax.swing.JLabel UsuarioPNG;
    private javax.swing.JSeparator UsuarioSeparator;
    private javax.swing.JLabel exitBottonText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel moveBar;
    // End of variables declaration//GEN-END:variables
}
